plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.multirkh'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security' //security context holder
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis' //redis

    // https://mvnrepository.com/artifact/io.hypersistence/hypersistence-utils-hibernate-63
    implementation 'io.hypersistence:hypersistence-utils-hibernate-63:3.9.11'

    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // https://mvnrepository.com/artifact/net.coobird/thumbnailator
    implementation 'net.coobird:thumbnailator:0.4.20'

    // https://mvnrepository.com/artifact/io.minio/minio
    implementation 'io.minio:minio:8.6.0'

    // mysql
    runtimeOnly 'com.mysql:mysql-connector-j'

    // https://mvnrepository.com/artifact/com.github.codemonstur/embedded-redis
    testImplementation 'com.github.codemonstur:embedded-redis:1.4.3'


    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'com.h2database:h2'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('cleanExtract', Delete) {
    dependsOn 'build'
    delete 'build/dependency'
}

tasks.register('extractJar', Copy) {
    dependsOn 'cleanExtract'
    from zipTree("build/libs/${project.name}-0.0.1-SNAPSHOT.jar")
    into 'build/dependency'
}
