spring.datasource.url=jdbc:mysql://mysql-container:3306/clone_database
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=redis-container
spring.data.redis.port=6379

minio.url=http://minio-container:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.thumbnail-bucket-name=minio-thumbnail
minio.bucket-name=minio-bucket
minio.export-url=http://localhost:9000

# jwt-set-uri
spring.security.oauth2.resourceserver.jwt.jwk-set-uri= http://keycloak-container:8080/realms/clone/protocol/openid-connect/certs

# SPA web origin
spa.web.origin=http://localhost:5173